name: Deploy FastAPI to Azure Container App

on:
  push:
    branches:
      - main
    paths:
      - "api/**"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ACR_NAME: youracrname
      RESOURCE_GROUP: your-resource-group
      CONTAINER_APP: your-container-app-name
      IMAGE_NAME: pokemon-api

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 🕒 Generate timestamp
        id: tag
        run: echo "TAG=$(date -u +'%Y-%m-%dT%H-%M-%S')" >> "$GITHUB_OUTPUT"

      - name: 🔐 Log in to Azure via OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 📦 Log in to ACR
        run: az acr login --name $ACR_NAME

      - name: 🛠️ Build & Push image
        run: |
          docker build --platform linux/amd64 \
            -t $ACR_NAME.azurecr.io/$IMAGE_NAME:latest \
            -t $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ steps.tag.outputs.TAG }} \
            -f api/Dockerfile .
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:latest
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ steps.tag.outputs.TAG }}

      - name: 🚀 Deploy to Container App
        run: |
          az containerapp update \
            --name $CONTAINER_APP \
            --resource-group $RESOURCE_GROUP \
            --image $ACR_NAME.azurecr.io/$IMAGE_NAME:latest
